{
 "title": "Seagate CORTX",
 "description": "Dashboard for Seagate CORTX",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "s3_server", "query": "{}" }
  ]
 },
 "panels": [
  {
   "title": "S3_server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput (bytes/s)",
     "type": "graph",
     "description": "Throughput of the S3_Server",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes trasferred per second" }
     ],
     "targets": [
      {
       "target": "alias(sumSeries(#A, #B), 'Total')",
       "targetFull": "alias(sumSeries(alias(movingAverage(perSecond($s3_server.gauges.haproxy.app-main.BACKEND.bout), '2min'), 'Write'), alias(movingAverage(perSecond($s3_server.gauges.haproxy.app-main.BACKEND.bin), '2min'), 'Read')), 'Total')"
      },
      {
       "refCount": -1,
       "target": "alias(movingAverage(perSecond($s3_server.gauges.haproxy.app-main.BACKEND.bin), '2min'), 'Read')"
      },
      {
       "refCount": 1,
       "target": "alias(movingAverage(perSecond($s3_server.gauges.haproxy.app-main.BACKEND.bout), '2min'), 'Write')"
      }
     ]
    },
    {
     "title": "IO (Ops/s)",
     "type": "graph",
     "description": "Object IOPS of the S3_Server",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ops", "label": "Ops per second" }
     ],
     "targets": [
      {
       "target": "alias(sumSeries(#B, #A), 'Total')",
       "targetFull": "alias(sumSeries(alias(sumSeries($s3_server.counters.get_object_request_count.rate, $s3_server.counters.get_multipart_parts_request_count.rate), 'Read'), alias(sumSeries($s3_server.counters.put_object_request_count.rate, $s3_server.counters.put_multipart_part_request_count.rate), 'Write')), 'Total')"
      },
      {
       "refCount": -1,
       "target": "alias(sumSeries($s3_server.counters.get_object_request_count.rate, $s3_server.counters.get_multipart_parts_request_count.rate), 'Read')"
      },
      {
       "refCount": 1,
       "target": "alias(sumSeries($s3_server.counters.put_object_request_count.rate, $s3_server.counters.put_multipart_part_request_count.rate), 'Write')"
      }
     ]
    },
    {
     "title": "Latency Object operations (ms)",
     "type": "graph",
     "description": "S3_Server latency for different operations",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      {
       "format": "ms",
       "label": "Average lantency (in millisecond)"
      }
     ],
     "targets": [
      {
       "target": "alias(averageSeries($s3_server.timers.create_object_success.mean, $s3_server.timers.multipart_create_object_success.mean, $s3_server.timers.chunkupload_create_object_success.mean), 'Create')"
      },
      {
       "target": "alias($s3_server.timers.read_object_data_success.mean, 'Read')"
      },
      {
       "target": "alias($s3_server.timers.write_to_clovis_op_success.mean, 'Write')"
      },
      {
       "target": "alias($s3_server.timers.get_keyval_success.mean, 'ReadKV')"
      },
      {
       "target": "alias($s3_server.timers.put_keyval_success.mean, 'WriteKV')"
      },
      {
       "target": "alias($s3_server.timers.delete_keyval_success.mean, 'DeleteKV')"
      },
      {
       "target": "alias(averageSeries($s3_server.timers.delete_objects_from_clovis_success.mean,$s3_server.timers.delete_object_from_clovis_success.mean), 'Delete')"
      }
     ]
    },
    {
     "title": "Metadata (Ops/s)",
     "type": "graph",
     "description": "Metadata operation per second.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops", "label": "Ops per second" }
     ],
     "targets": [
      {
       "target": "alias(sumSeries(#A, #F, #G, #H, #I, #K, #L, #M, #N, #O), 'Total')",
       "targetFull": "alias(sumSeries(alias(sumSeries($s3_server.counters.delete_object_request_count.rate, $s3_server.counters.delete_multiobject_request_count.rate), 'Delete'), alias($s3_server.counters.get_object_acl_request_count.rate, 'Acl Get'), alias($s3_server.counters.put_object_acl_request_count.rate, 'Acl Put'), alias($s3_server.counters.post_multipart_complete_request_count.rate, 'Multipart Complete'), alias($s3_server.counters.post_multipart_initiate_request_count.rate, 'Multipart Initiate'), alias($s3_server.counters.abort_multipart_request_count.rate, 'Multipart Abort'), alias($s3_server.counters.head_object_request_count.rate, 'Head'), alias($s3_server.counters.put_object_chunkupload_request_count.rate, 'Chunkupload Put'), alias($s3_server.counters.unsupported_api_count.rate, 'Unsupprted API'), alias($s3_server.counters.get_service_request_count.rate, 'Get Service')), 'Total')"
      },
      {
       "refCount": 1,
       "target": "alias(sumSeries($s3_server.counters.delete_object_request_count.rate, $s3_server.counters.delete_multiobject_request_count.rate), 'Delete')"
      },
      {
       "refCount": 1,
       "target": "alias($s3_server.counters.get_object_acl_request_count.rate, 'Acl Get')"
      },
      {
       "refCount": 1,
       "target": "alias($s3_server.counters.put_object_acl_request_count.rate, 'Acl Put')"
      },
      {
       "refCount": 1,
       "target": "alias($s3_server.counters.post_multipart_complete_request_count.rate, 'Multipart Complete')"
      },
      {
       "refCount": 1,
       "target": "alias($s3_server.counters.post_multipart_initiate_request_count.rate, 'Multipart Initiate')"
      },
      {
       "refCount": 1,
       "target": "alias($s3_server.counters.abort_multipart_request_count.rate, 'Multipart Abort')"
      },
      {
       "refCount": 1,
       "target": "alias($s3_server.counters.head_object_request_count.rate, 'Head')"
      },
      {
       "refCount": 1,
       "target": "alias($s3_server.counters.put_object_chunkupload_request_count.rate, 'Chunkupload Put')"
      },
      {
       "refCount": 1,
       "target": "alias($s3_server.counters.unsupported_api_count.rate, 'Unsupprted API')"
      },
      {
       "refCount": 1,
       "target": "alias($s3_server.counters.get_service_request_count.rate, 'Get Service')"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity (bytes)",
     "type": "grafana-piechart-panel",
     "description": "Cpacity for mero cluster",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "target": "alias(cluster.gauges.mero.free_space, 'Free Space')"
      },
      {
       "target": "alias(cluster.gauges.mero.used_space, 'Used Space')"
      }
     ]
    },
    {
     "title": "Throughput (bytes/s)",
     "type": "graph",
     "description": "Throughput of the cluster",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes trasferred per second" }
     ],
     "targets": [
      {
       "target": "alias(sumSeries(#A, #B), 'Total')",
       "targetFull": "alias(sumSeries(alias(movingAverage(perSecond(cluster.gauges.haproxy.app-main.BACKEND.bin), '2min'), 'Write'), alias(movingAverage(perSecond(cluster.gauges.haproxy.app-main.BACKEND.bout), '2min'), 'Read')), 'Total')"
      },
      {
       "refCount": -1,
       "target": "alias(movingAverage(perSecond(cluster.gauges.haproxy.app-main.BACKEND.bout), '2min'), 'Read')"
      },
      {
       "refCount": 1,
       "target": "alias(movingAverage(perSecond(cluster.gauges.haproxy.app-main.BACKEND.bin), '2min'), 'Write')"
      }
     ]
    },
    {
     "title": "IO (Ops/s)",
     "type": "graph",
     "description": "Object IOPS of the cluster",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ops", "label": "Ops per second" }
     ],
     "targets": [
      {
       "target": "alias(sumSeries(#B, #A), 'Total')",
       "targetFull": "alias(sumSeries(alias(sumSeries(cluster.counters.get_object_request_count.rate, cluster.counters.get_multipart_parts_request_count.rate), 'Read'), alias(sumSeries(cluster.counters.put_object_request_count.rate, cluster.counters.put_multipart_part_request_count.rate), 'Write')), 'Total')"
      },
      {
       "refCount": -1,
       "target": "alias(sumSeries(cluster.counters.get_object_request_count.rate, cluster.counters.get_multipart_parts_request_count.rate), 'Read')"
      },
      {
       "refCount": 1,
       "target": "alias(sumSeries(cluster.counters.put_object_request_count.rate, cluster.counters.put_multipart_part_request_count.rate), 'Write')"
      }
     ]
    },
    {
     "title": "Latency Object operations (ms)",
     "type": "graph",
     "description": "Cluster latency for different operations",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      {
       "format": "ms",
       "label": "Average lantency (in millisecond)"
      }
     ],
     "targets": [
      {
       "target": "alias(averageSeries(cluster.timers.create_object_success.mean, cluster.timers.multipart_create_object_success.mean, cluster.timers.chunkupload_create_object_success.mean), 'Create')"
      },
      {
       "target": "alias(cluster.timers.read_object_data_success.mean, 'Read')"
      },
      {
       "target": "alias(cluster.timers.write_to_clovis_op_success.mean, 'Write')"
      },
      {
       "target": "alias(cluster.timers.get_keyval_success.mean, 'ReadKV')"
      },
      {
       "target": "alias(cluster.timers.put_keyval_success.mean, 'WriteKV')"
      },
      {
       "target": "alias(cluster.timers.delete_keyval_success.mean, 'DeleteKV')"
      },
      {
       "target": "alias(averageSeries(cluster.timers.delete_objects_from_clovis_success.mean, cluster.timers.delete_object_from_clovis_success.mean), 'Delete')"
      }
     ]
    },
    {
     "title": "Metadata (Ops/s)",
     "type": "graph",
     "description": "Metadata operation per second.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "ops", "label": "Ops per second" }
     ],
     "targets": [
      {
       "target": "alias(sumSeries(#A, #F, #G, #H, #I, #K, #L, #M, #N, #O), 'Total')",
       "targetFull": "alias(sumSeries(alias(sumSeries(cluster.counters.delete_object_request_count.rate, cluster.counters.delete_multiobject_request_count.rate), 'Delete'), alias(cluster.counters.get_object_acl_request_count.rate, 'ACL Get'), alias(cluster.counters.put_object_acl_request_count.rate, 'ACL Put'), alias(cluster.counters.post_multipart_complete_request_count.rate, 'Multipart Complete'), alias(cluster.counters.post_multipart_initiate_request_count.rate, 'Multipart Initiate'), alias(cluster.counters.abort_multipart_request_count.rate, 'Multipart Abort'), alias(cluster.counters.head_object_request_count.rate, 'Head'), alias(cluster.counters.put_object_chunkupload_request_count.rate, 'Chunkupload Put'), alias(cluster.counters.unsupported_api_count.rate, 'Unsupprted API'), alias(cluster.counters.get_service_request_count.rate, 'Get Service')), 'Total')"
      },
      {
       "refCount": 1,
       "target": "alias(sumSeries(cluster.counters.delete_object_request_count.rate, cluster.counters.delete_multiobject_request_count.rate), 'Delete')"
      },
      {
       "refCount": 1,
       "target": "alias(cluster.counters.get_object_acl_request_count.rate, 'ACL Get')"
      },
      {
       "refCount": 1,
       "target": "alias(cluster.counters.put_object_acl_request_count.rate, 'ACL Put')"
      },
      {
       "refCount": 1,
       "target": "alias(cluster.counters.post_multipart_complete_request_count.rate, 'Multipart Complete')"
      },
      {
       "refCount": 1,
       "target": "alias(cluster.counters.post_multipart_initiate_request_count.rate, 'Multipart Initiate')"
      },
      {
       "refCount": 1,
       "target": "alias(cluster.counters.abort_multipart_request_count.rate, 'Multipart Abort')"
      },
      {
       "refCount": 1,
       "target": "alias(cluster.counters.head_object_request_count.rate, 'Head')"
      },
      {
       "refCount": 1,
       "target": "alias(cluster.counters.put_object_chunkupload_request_count.rate, 'Chunkupload Put')"
      },
      {
       "refCount": 1,
       "target": "alias(cluster.counters.unsupported_api_count.rate, 'Unsupprted API')"
      },
      {
       "refCount": 1,
       "target": "alias(cluster.counters.get_service_request_count.rate, 'Get Service')"
      }
     ]
    }
   ]
  },
  {
   "title": "S3 Server Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Server Error (count)",
     "type": "graph",
     "description": "S3server Error",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "locale", "label": "Error count" }
     ],
     "targets": [
      {
       "target": "alias(sumSeries($s3_server.timers.create_object_failed.count, $s3_server.timers.multipart_create_object_failed.count, $s3_server.timers.chunkupload_create_object_failed.count), 'Create Object')"
      },
      {
       "target": "alias(sumSeries($s3_server.timers.delete_object_from_clovis_failed.count, $s3_server.timers.delete_objects_from_clovis_failed.count), 'Delete Object')"
      },
      {
       "target": "alias($s3_server.timers.read_object_data_failed.count, 'Get Object')"
      },
      {
       "target": "alias($s3_server.timers.write_to_clovis_op_failed.count, 'Put Object')"
      },
      {
       "target": "alias($s3_server.timers.create_index_op_failed.count, 'Create Index')"
      },
      {
       "target": "alias($s3_server.timers.delete_index_op_failed.count, 'Delete Index')"
      },
      {
       "target": "alias($s3_server.timers.get_keyval_failed.count, 'Get Keyval')"
      },
      {
       "target": "alias($s3_server.timers.put_keyval_failed.count, 'Put Keyval')"
      },
      {
       "target": "alias($s3_server.timers.delete_keyval_failed.count, 'Delete Keyval')"
      },
      {
       "target": "alias($s3_server.counters.internal_error_count.count, 'Internal Error')"
      }
     ]
    },
    {
     "title": "Haproxy Error (count)",
     "type": "graph",
     "description": "Haproxy Error",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "locale", "label": "Error count" }
     ],
     "targets": [
      {
       "target": "alias(derivative($s3_server.gauges.haproxy.app-main.BACKEND.hrsp_4xx), 'HTTP Client')"
      },
      {
       "target": "alias(derivative($s3_server.gauges.haproxy.app-main.BACKEND.hrsp_5xx), 'HTTP Server')"
      },
      {
       "target": "alias(derivative($s3_server.gauges.haproxy.app-main.BACKEND.econ), 'Connection')"
      }
     ]
    },
    {
     "title": "Auth Server Error (count)",
     "type": "graph",
     "description": "Auth Server Error",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "locale", "label": "Error count" }
     ],
     "targets": [
      {
       "target": "alias($s3_server.counters.authentication_failed_invalid_accesskey_count.count, 'Invalid Access Key')"
      },
      {
       "target": "alias($s3_server.counters.authentication_failed_signature_mismatch_count.count, 'Signature Mismatch')"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Error",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "S3 Server Error (count)",
     "type": "graph",
     "description": "S3server Error",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "locale", "label": "Error count" }
     ],
     "targets": [
      {
       "target": "alias(sumSeries(cluster.timers.create_object_failed.count, cluster.timers.multipart_create_object_failed.count, cluster.timers.chunkupload_create_object_failed.count), 'Create Object')"
      },
      {
       "target": "alias(sumSeries(cluster.timers.delete_object_from_clovis_failed.count, cluster.timers.delete_objects_from_clovis_failed.count), 'Delete Object')"
      },
      {
       "target": "alias(cluster.timers.read_object_data_failed.count, 'Get Object')"
      },
      {
       "target": "alias(cluster.timers.write_to_clovis_op_failed.count, 'Put Object')"
      },
      {
       "target": "alias(cluster.timers.create_index_op_failed.count, 'Create Index')"
      },
      {
       "target": "alias(cluster.timers.delete_index_op_failed.count, 'Delete Index')"
      },
      {
       "target": "alias(cluster.timers.get_keyval_failed.count, 'Get Keyval')"
      },
      {
       "target": "alias(cluster.timers.put_keyval_failed.count, 'Put Keyval')"
      },
      {
       "target": "alias(cluster.timers.delete_keyval_failed.count, 'Delete Keyval')"
      },
      {
       "target": "alias(cluster.counters.internal_error_count.count, 'Internal Error')"
      }
     ]
    },
    {
     "title": "Haproxy Error (count)",
     "type": "graph",
     "description": "Haproxy Error",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "locale", "label": "Error count" }
     ],
     "targets": [
      {
       "target": "alias(derivative(cluster.gauges.haproxy.app-main.BACKEND.hrsp_4xx), 'HTTP Client')"
      },
      {
       "target": "alias(derivative(cluster.gauges.haproxy.app-main.BACKEND.hrsp_5xx), 'HTTP Server')"
      },
      {
       "target": "alias(derivative(cluster.gauges.haproxy.app-main.BACKEND.econ), 'Connection')"
      }
     ]
    },
    {
     "title": "Auth Server Error (count)",
     "type": "graph",
     "description": "Auth Server Error",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "locale", "label": "Error count" }
     ],
     "targets": [
      {
       "target": "alias(cluster.counters.authentication_failed_invalid_accesskey_count.count, 'Invalid Access Key')"
      },
      {
       "target": "alias(cluster.counters.authentication_failed_signature_mismatch_count.count, 'Signature Mismatch')"
      }
     ]
    }
   ]
  }
 ]
}