---
- hosts: kubernetes-worker-nodes
  become: true
  tasks:

  - name: Copying token to worker nodes
    copy:
      src: /token_file
      dest: join_token

  - name: Resetting kubeadm 
    command: kubeadm reset --force

  - name: Joining worker nodes with kubernetes master
    command: sh join_token
